version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    labels:
      - area/dependencies
      - type/maintenance
    commit-message:
      prefix: deps
    groups:
      development-tools:
        dependency-type: development
      runtime-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    labels:
      - area/ci
      - type/maintenance
    commit-message:
      prefix: ci
