"""Canonical domain value objects for LudoWright."""

from ludowright.domain.errors import (
    DomainValidationError,
    InvalidApprovalError,
    InvalidApprovalTransitionError,
    InvalidDecisionError,
    InvalidDecisionTransitionError,
    InvalidIdentifierError,
    InvalidNameError,
    InvalidProjectError,
    InvalidProjectTransitionError,
    InvalidVersionError,
)
from ludowright.domain.governance import (
    Approval,
    ApprovalRevision,
    ApprovalStatus,
    ApprovalSubject,
    Decision,
    DecisionRevision,
    DecisionStatus,
    ReviewNote,
    SubjectRevision,
)
from ludowright.domain.identifiers import (
    ApprovalId,
    AssetId,
    ComponentId,
    DecisionId,
    Identifier,
    JobId,
    PackageId,
    ProjectId,
    ReferenceId,
)
from ludowright.domain.names import DisplayName, slugify, validate_slug
from ludowright.domain.project import (
    EngineSpec,
    PlatformFamily,
    Project,
    ProjectDimension,
    ProjectIdentity,
    ProjectLifecycle,
    ProjectStage,
    ProjectTarget,
)
from ludowright.domain.versions import (
    ProfileVersion,
    RevisionVersion,
    SchemaVersion,
    TemplateVersion,
)

__all__ = [
    "Approval",
    "ApprovalId",
    "ApprovalRevision",
    "ApprovalStatus",
    "ApprovalSubject",
    "AssetId",
    "ComponentId",
    "Decision",
    "DecisionId",
    "DecisionRevision",
    "DecisionStatus",
    "DisplayName",
    "DomainValidationError",
    "EngineSpec",
    "Identifier",
    "InvalidApprovalError",
    "InvalidApprovalTransitionError",
    "InvalidDecisionError",
    "InvalidDecisionTransitionError",
    "InvalidIdentifierError",
    "InvalidNameError",
    "InvalidProjectError",
    "InvalidProjectTransitionError",
    "InvalidVersionError",
    "JobId",
    "PackageId",
    "PlatformFamily",
    "ProfileVersion",
    "Project",
    "ProjectDimension",
    "ProjectId",
    "ProjectIdentity",
    "ProjectLifecycle",
    "ProjectStage",
    "ProjectTarget",
    "ReferenceId",
    "ReviewNote",
    "RevisionVersion",
    "SchemaVersion",
    "SubjectRevision",
    "TemplateVersion",
    "slugify",
    "validate_slug",
]
